Repository sandrolovnicki/pLam, pull requests merged in 2019-09, with the labels that each got.

#9 dev + export-command
  README.md
  app/Main.hs
  pLam.cabal
  src/Helper.hs
  src/Parser.hs
  src/Syntax.hs
Labels: feature

#15 Tweak Haskeline settings to use a history file named .plam-history
  app/Main.hs
Labels: enhancement, feature

#16 Removes redundant code and a few unnecessary `do`s
  app/Main.hs
  src/Helper.hs
Labels: enhancement
